<?php
include(drupal_get_path('module','spy_manip').'/includes/spy_manip.functions.inc');

/**
 * Implements hook_form_alter().
 */
function spy_manip_form_alter(&$form, &$form_state, $form_id){
    if(!array_key_exists('#user',$form) && !array_key_exists('#node',$form) && !array_key_exists('#term',$form) ){
        $form['#submit'][] = 'spy_manip_form_submit';
    }
}

/**
* Submit log manip
**/
function spy_manip_form_submit($form, &$form_state){
  $change = array(
    'form' => $form['#id'],
    'change' => ''
  );
  spy_manip_log_manip($change);
}


/**
 * Implements hook_node_presave().
 */
function spy_manip_node_presave($node) {
  $fields_changed = spy_manip_fields_changed_node($node->original, $node, $node->type);
  if(!empty($fields_changed)){
    $change = array(
      'form' => $node->type."-node-form",
      'change' => implode(",", $fields_changed)
    );
    spy_manip_log_manip($change);
  }
}

/**
 * Implements hook_taxonomy_term_presave().
 */
function spy_manip_taxonomy_term_presave($term) {
  $fields_changed = spy_manip_fields_changed_term($term->original, $term);
  if(!empty($fields_changed)){
    $change = array(
      'form' => "taxonomy-form-term (".$term->vocabulary_machine_name.")",
      'change' => implode(",", $fields_changed)
    ); 
    spy_manip_log_manip($change);
  }
}

/**
 * Implements hook_user_presave().
 */
function spy_manip_user_presave(&$edit, $account, $category) {
  $fields_changed = spy_manip_fields_changed_user($edit, $account->original);
  $change = array(
    'form' => "user-profile-form (".$account->uid.")",
    'change' => ''
  ); 
  spy_manip_log_manip($change);
}